version: '3'
services:
  web:
    container_name: muchat_go
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: muchat_db
    image: mysql:8.0
#    volumes:
#      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatgpt
      MYSQL_USER: ubuntu
      MYSQL_PASSWORD: ubuntu
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci