api_platform:
  base_url: https://api.openai.com/v1/
concurrency: 7            # 系统内向 ChatGPT 发送请求的最大并发数
listen: 0.0.0.0:8080
censor_enabled: true      # 是否启用敏感词过滤
open_ai_account:
  query_interval: 5m      # OpenAI 账户检查间隔
  concurrency: 4          # 同时启用的 OpenAI 账户数量
guests:                   # 游客模式
  - enabled: true
    max_usage: 10         # 每个游客（IP）最大使用次数，不会重置
    domain: localhost     # 启用游戏模式的域名，不包含端口
  - enabled: true
    max_usage: 10
    domain: ai6.top
mock:
  enabled: false
  response: 正在调试中
  free_of_charge: false
gpt:                      # GPT-3 配置，3.5开放之后不再使用
  auto_pass: true
  session_timeout: 60
  max_tokens: 2048
  model: text-davinci-003
  temperature: 0.7
  reply_prefix: 来自机器人回复：
db:
  host: 127.0.0.1
  name: muchat
  user: ubuntu
  pass: ubuntu
tencent_cos:
  secret_id: ''
  secret_key: ''
  bucket_url: https://chatgpt-.cos.ap-guangzhou.myqcloud.com
  ci_url: https://chatgpt-.ci.ap-guangzhou.myqcloud.com
  service_url: https://service.cos.myqcloud.com
baidu_ai:
  app_key:
  secret_key: